#!/usr/bin/env python3
"""Development-only College Decision Room shell and lazy client renderer."""

COLLEGE_PAYLOAD_URL = "/data/decision-room-college.json"

SHELL = '''
<main id="college-decision-room" class="dr-shell cdr" hidden aria-busy="true">
  <section class="dr-hero">
    <div class="dr-kicker">College Fantasy Football</div>
    <div class="dr-mode">Validated weekly mode · Yahoo scoring</div>
    <h1 id="cdr-title">College Decision Room</h1>
    <p class="dr-lede">Compare validated college projections and see the exact boundary that changes the recommendation.</p>
    <p id="cdr-meta" class="dr-week-note">Loading the validated college projection release…</p>
    <p class="dr-week-note">Validated scope: 2,205 players across 64 teams · Yahoo scoring only · no player images, ADP, or conference metadata.</p>
    <section class="dr-compare" aria-labelledby="cdr-compare-title">
      <div class="dr-compare-head"><div><small>College decision</small><h2 id="cdr-compare-title">Player vs. player</h2></div><strong>Yahoo scoring</strong></div>
      <div class="cdr-filters"><label>Position<select id="cdr-position"><option value="">All positions</option><option>QB</option><option>RB</option><option>WR</option><option>TE</option></select></label><label>Team<select id="cdr-team"><option value="">All teams</option></select></label></div>
      <div class="dr-selectors"><label>Player one<input id="cdr-a" type="search" list="cdr-a-list" autocomplete="off"><datalist id="cdr-a-list"></datalist></label><b>VS</b><label>Player two<input id="cdr-b" type="search" list="cdr-b-list" autocomplete="off"><datalist id="cdr-b-list"></datalist></label></div>
      <label class="dr-cross"><input type="checkbox" id="cdr-cross-position"> Compare across positions</label>
      <div id="cdr-result" aria-live="polite"></div>
    </section>
  </section>
  <section class="dr-section"><div class="dr-section-head"><div><small>Decision pressure</small><h2>Closest Calls</h2></div><p>Same-position Week 1 projections with the smallest displayed point gaps.</p></div><div id="cdr-closest" class="dr-card-grid"></div></section>
  <section class="dr-section"><div class="dr-section-head"><div><small>Separation</small><h2>Strongest Projection Edges</h2></div><p>Largest adjacent same-position edges in the validated Week 1 rankings.</p></div><div id="cdr-edges" class="dr-card-grid"></div></section>
  <section class="dr-section"><div class="dr-section-head"><div><small>Format sensitivity</small><h2>Scoring-Format Movers</h2></div></div><article class="dr-empty"><h3>One validated scoring format</h3><p>The college release currently supports Yahoo scoring only, so scoring-format movement or reversals cannot be calculated honestly.</p></article></section>
  <section class="dr-future-grid"><article class="dr-empty"><small>Coming next</small><h2>Decision Inbox</h2><p>Connect your college league to see the decisions that matter on your roster.</p><button disabled>College league sync not yet available</button></article><article class="dr-empty"><small>Accountability layer</small><h2>Decision Record</h2><p>No college decisions have been recorded. Future snapshots will preserve the recommendation, inputs, timestamp, and outcome.</p><div class="dr-empty-line">No saved college decisions yet</div></article></section>
  <nav class="dr-tools" aria-label="College fantasy tools"><span>College tools</span><a href="/college-fantasy-football/week-1/">Week 1 rankings</a><a href="/college-fantasy-football/projections/">Season projections</a><a href="/decision-room/college/" aria-current="page">College Decision Room</a></nav>
</main>'''

JS = r'''(()=>{const root=document.getElementById('college-decision-room'),nfl=document.getElementById('decision-room'),Q=new URLSearchParams(location.search),sport=location.pathname.includes('/decision-room/college')||document.body.dataset.defaultSport==='college'?'college':(Q.get('sport')||'nfl');document.querySelectorAll('[data-sport]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.sport===sport?'true':'false'));if(sport!=='college')return;if(nfl)nfl.hidden=true;root.hidden=false;document.title='College Week 1 Decision Room | Lineup Beat';fetch('/data/decision-room-college.json',{credentials:'same-origin'}).then(r=>{if(!r.ok)throw Error('college data unavailable');return r.json()}).then(D=>{if(D.sport!=='college'||D.mode!=='weekly')throw Error('invalid college payload');root.setAttribute('aria-busy','false');const P=Object.fromEntries(D.players.map(p=>[p.id,p])),label=p=>`${p.name} · ${p.team} ${p.position}`,byLabel=Object.fromEntries(D.players.map(p=>[label(p),p])),A=document.getElementById('cdr-a'),B=document.getElementById('cdr-b'),AL=document.getElementById('cdr-a-list'),BL=document.getElementById('cdr-b-list'),POS=document.getElementById('cdr-position'),TEAM=document.getElementById('cdr-team'),X=document.getElementById('cdr-cross-position'),O=document.getElementById('cdr-result'),num=v=>Number(v).toFixed(1),shown=p=>Number(Number(p.formats.yahoo.projected_points).toFixed(1)),conf=g=>g===0?'True Toss-Up':g<=2?'Toss-Up':g<12?'Lean':'Clear Edge';
document.getElementById('cdr-title').textContent=D.title;document.getElementById('cdr-meta').textContent=`${D.projection_horizon} · 2026 · Week ${D.week} · ${D.scoring_label} · Projection data updated ${D.updated_at}`;[...new Set(D.players.map(p=>p.team))].sort().forEach(t=>TEAM.add(new Option(t,t)));
function pool(which){let rows=D.players.filter(p=>(!POS.value||p.position===POS.value)&&(!TEAM.value||p.team===TEAM.value));let a=byLabel[A.value];if(which===B&&!X.checked&&a)rows=rows.filter(p=>p.position===a.position);return rows}
function lists(){AL.innerHTML=pool(A).map(p=>`<option value="${label(p)}"></option>`).join('');BL.innerHTML=pool(B).map(p=>`<option value="${label(p)}"></option>`).join('')}
function crest(p){return `<div class="cdr-crest" aria-hidden="true">${p.team.split(/\s+/).map(x=>x[0]).join('').slice(0,3)}</div>`}
function cards(a,b){return `<div class="dr-player-grid"><article><div class="dr-person">${crest(a)}<div><small>${a.team} · ${a.position}</small><h3>${a.name}</h3></div></div><dl><div><dt>Projected points</dt><dd>${num(shown(a))}</dd></div><div><dt>Overall rank</dt><dd>#${a.formats.yahoo.overall_rank}</dd></div><div><dt>Position rank</dt><dd>${a.position}${a.formats.yahoo.position_rank}</dd></div></dl></article><article><div class="dr-person">${crest(b)}<div><small>${b.team} · ${b.position}</small><h3>${b.name}</h3></div></div><dl><div><dt>Projected points</dt><dd>${num(shown(b))}</dd></div><div><dt>Overall rank</dt><dd>#${b.formats.yahoo.overall_rank}</dd></div><div><dt>Position rank</dt><dd>${b.position}${b.formats.yahoo.position_rank}</dd></div></dl></article></div>`}
function draw(){let a=byLabel[A.value],b=byLabel[B.value];if(!a||!b||a.id===b.id){O.innerHTML='<p class="dr-error">Choose two different college players.</p>';return}let ap=shown(a),bp=shown(b),gap=Math.abs(ap-bp),w=ap===bp?null:(ap>bp?a:b),r=w?(w.id===a.id?b:a):null;if(!w){O.innerHTML=`<section class="dr-verdict"><div><small>True Toss-Up · Yahoo</small><h2>No clear edge</h2><p>Both players display at ${num(ap)} Week 1 points. Neither player is recommended.</p></div></section>${cards(a,b)}<section class="dr-boundary"><h2>What changes the pick?</h2><p>Either player needs 0.1 additional displayed Week 1 point to move ahead.</p></section>`;return}let flip=+(gap+.1).toFixed(1);O.innerHTML=`<section class="dr-verdict"><div><small>${conf(gap)} · Yahoo</small><h2>Recommend ${w.name}</h2><p>${w.name} projects for ${num(shown(w))} Week 1 points, ${num(gap)} more than ${r.name}. The recommendation follows the higher validated projection.</p></div><div class="dr-adv"><b>+${num(gap)}</b><span>Week 1 point advantage</span></div></section>${cards(a,b)}<section class="dr-boundary"><div class="dr-boundary-title"><small>Decision boundary</small><h2>What changes the pick?</h2></div><div class="dr-boundary-grid"><article><b>+${num(flip)}</b><span>${r.name} needs this many additional projected Week 1 points to move ahead.</span></article><article><b>−${num(flip)}</b><span>${w.name} could lose this many projected Week 1 points before the pick flips.</span></article><article><b>Yahoo only</b><span>No scoring-format reversal can be calculated from one validated format.</span></article><article><b>No ADP</b><span>Validated college ADP is not available, so no market comparison is shown.</span></article></div></section><p class="dr-stamp">Projection data updated ${D.updated_at} · 2026 Week 1 · ${D.scoring_label}</p>`}
function mini(x){let a=P[x.a],b=P[x.b],w=x.winner?P[x.winner]:null;return `<article class="dr-mini"><div class="dr-mini-pair"><span>${a.name}</span><i>${w?'over':'tied with'}</i><span>${b.name}</span></div><p>${a.position}${a.formats.yahoo.position_rank} vs ${b.position}${b.formats.yahoo.position_rank} · ${num(x.gap)}-point gap · ${x.confidence}</p><p class="dr-recommendation">${w?'Recommend '+w.name:'No clear edge'}</p><button type="button" class="cdr-open" data-a="${x.a}" data-b="${x.b}">Compare</button></article>`}document.getElementById('cdr-closest').innerHTML=D.closest_calls.map(mini).join('');document.getElementById('cdr-edges').innerHTML=D.strongest_edges.map(mini).join('');let first=D.closest_calls[0],pa=P[first.a],pb=P[first.b];A.value=label(pa);B.value=label(pb);lists();draw();A.addEventListener('change',()=>{let a=byLabel[A.value];if(a&&!X.checked){let b=pool(B).find(p=>p.id!==a.id);if(b)B.value=label(b)}lists();draw()});B.addEventListener('change',draw);[POS,TEAM,X].forEach(x=>x.addEventListener('change',()=>{lists();draw()}));document.querySelectorAll('.cdr-open').forEach(x=>x.addEventListener('click',()=>{A.value=label(P[x.dataset.a]);B.value=label(P[x.dataset.b]);draw();document.getElementById('cdr-compare-title').scrollIntoView({behavior:'smooth'})}))}).catch(()=>{root.setAttribute('aria-busy','false');document.getElementById('cdr-meta').textContent='Validated college projection data could not be loaded.'})})();'''
