const assert = require('node:assert/strict');
const {normalize,gameStatus} = require('../assets/score-ticker.js');
const fs=require('node:fs');
assert.deepEqual(normalize({games:[]}),[]);
assert.throws(()=>normalize({events:[]}));
assert.equal(gameStatus({state:'in',detail:'Live'}),'Live');
assert.equal(gameStatus({state:'pre',timeValid:false}),'Time TBD');
const source=fs.readFileSync('assets/score-ticker.js','utf8');
assert(!/espn/i.test(source));
assert(source.includes('https://scores.lineupbeat.com/'));
console.log('Score ticker checks passed');
